src/CouchDB.Client/CouchDocuments.cs, src/CouchDB.Client/CouchQueryable.cs, src/CouchDB.Client/Query/ICouchQueryable.cs
I ran into a case where I built 2 queries before executing them, but the 2nd one overwrote the 1st. I split the query properties out into a dedicated `Queryable` object so multiple queries don't step on each other
=> Separate queryable object

src/CouchDB.Client/CouchClient.cs
Every request was generating a new login request instead of reusing the auth token because the expiration check was backwards
=> Refresh auth token when it expires, not when it hasn't expired

src/CouchDB.Client/CouchClient.cs
Removes client cert validation added by #1. It doesn't work if you need to recreate a client. A better approach is to configure it using Flurl from the calling application.
```
FlurlHttp.ConfigureClient(serverUri.ToString(), c =>
{
c.Settings.HttpClientFactory = new CertClientFactory();
});
public class OcuveraCertClientFactory : DefaultHttpClientFactory
{
public override HttpMessageHandler CreateMessageHandler()
{
return new HttpClientHandler()
{
ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
{
// TODO Implement actual cert validation
return true;
}
};
}
}
```
=> Remove client cert validation

src/CouchDB.Client.Tests/CouchDB.Client.Tests.csproj, src/CouchDB.Client.Tests/SelectorTests.cs, src/CouchDB.Client/Properties/AssemblyInfo.cs, src/CouchDB.Client/Query/Selector/SelectorNodesBuilder.cs, src/CouchDB.Client/Query/Selector/SelectorObjectBuilder.cs, src/CouchDB.sln
I ran into some bugs trying to use expressions to generate selectors.
A couple failure cases that I needed:
```
const int one = 1;
Expression<Func<MyDocument, bool>> query = t => t.MyInt == one;
```
```
var comparisonDoc = new MyDocument { MyInt = 1 };
Expression<Func<MyDocument, bool>> query = t => t.MyInt >= comparisonDoc.MyInt;
```
I was a little worried about breaking other functionality, so I wrote some unit tests to cover others too. I'm good with my implementation getting blown away by the queryable branch you're working on, but I think it's important that these use cases still work and are tested.
=> SelectorBuilder tests and tweaks

src/CouchDB.Driver/CouchDB.Driver.csproj, src/CouchDB.Driver/Helpers/RequestsHelper.cs
I was getting deadlocks from the `.Result`. https://stackoverflow.com/a/9343733/1130636
=> Prevent async deadlocks

src/CouchDB.Driver/Extensions/EnumerableExtensions.cs, src/CouchDB.Driver/Extensions/ObjectExtensions.cs, tests/CouchDB.Driver.UnitTests/Find/Find_Selector_Conditions.cs
I needed `.In()` with a Guid, but Guid doesn't doesn't implement `IConvertible`. I couldn't find anything actually using IConvertible, so I just removed the constraint
=> Allow more types for .In() and .Contains()

src/CouchDB.Driver/Translators/ConstantExpressionTranslator.cs, src/CouchDB.Driver/Translators/MethodCallExpressionTranslator.cs, tests/CouchDB.Driver.UnitTests/Find/Find_Selector_Conditions.cs
`_rebels.Where(r => r.Age.In(new[] { 20 }))` was querying with `{"age":{"$in":20}}}`, which CouchDb doesn't like. It looks like the special handling of 1 item arrays was in there for `UseIndex()`, so I moved that special case handling to UseIndex and let the rest of arrays include square brackets.
The last commit removes the 2nd constant handler and shares the 1st to reduce duplication. The change isn't strictly necessary, but I think it increases maintainability. If there's a side effect I'm not aware of, I'm happy to revert that
=> Support querying with single item array

README.md, src/CouchDB.Driver/CouchDatabase.cs, tests/CouchDB.Driver.UnitTests/Database_Tests.cs
Provides a workaround for query edge cases that aren't supported
=> Support for direct queries without using the LINQ api

src/CouchDB.Driver/ExpressionVisitors/BoolMemberToConstantEvaluator.cs, tests/CouchDB.Driver.E2ETests/Client_Tests.cs, tests/CouchDB.Driver.UnitTests/Find/Find_Selector_Combinations.cs, tests/CouchDB.Driver.UnitTests/_Models/Battle.cs, tests/CouchDB.Driver.UnitTests/_Models/Vehicle.cs
`_rebels.Where(r => r.Battles.Any(b => b.DidWin))` was querying with `{"selector":{"battles":{"$elemMatch":"didWin"}}}` instead of `{"selector":{"battles":{"$elemMatch":{"didWin":true}}}}`. To fix, I changed it so the `BoolMemberToConstantEvaluator` processes all children of a `.Where()` instead of resetting at the next method call
=> Implicit bools in nested methods

src/CouchDB.Driver/CouchClient.cs, src/CouchDB.Driver/Settings/CouchSettings.cs
I ran into a situation where the CouchClient finalizer was deadlocking a unit test if run from .NET Framework. It doesn't affect .NET Core because of changes to the async context in .NET Core.
I didn't commit my unit test because it didn't feel worth an extra project to have .NET Framework only tests, but here's the test in case you're interested. When run against .NET Framework, it shows success, but the test runner never completes.
```
[TestMethod]
public void FinalizerHangs()
{
var client = new CouchClient("http://localhost");
}
```
I also limited when `Dispose()` calls `Logoff()`. It's not needed for Basic or Anonymous auth. I also added an opt-out setting for cookie auth.
If it's not too much trouble, I would appreciate if you kicked a build (even if it's just prerelease). Thanks!
=> Finalizer deadlock

src/CouchDB.Driver/CouchQueryProvider.cs, src/CouchDB.Driver/Exceptions/CouchConflictException.cs, src/CouchDB.Driver/Exceptions/CouchException.cs, src/CouchDB.Driver/Exceptions/CouchNoIndexException.cs, src/CouchDB.Driver/Exceptions/CouchNotFoundException.cs, src/CouchDB.Driver/Helpers/RequestsHelper.cs, tests/CouchDB.Driver.UnitTests/Client_Tests.cs
I was running into NullReferenceExceptions if there wasn't a message/reason returned for an error. I started looking at exception handling with an eye on diagnosing from the outside and think these changes should help.
- We were null checking for known exception types, but unknown ones were assuming a message would be available. This would lead to `NullReferenceException` for lots of unhappy paths like when the db server is offline
- While testing, I noticed that `CouchNoIndexException` was being wrapped inside a `TargetInvocationException`. I unwrapped that so it's easier to catch
- It was bothering me that the underlying http exceptions couldn't be seen in the exception info, so I added the `FlurlHttpException` as the `InnerException` and moved `Reason` to it's own property
=> Exception handling

src/CouchDB.Driver/Translators/ConstantExpressionTranslator.cs, tests/CouchDB.Driver.UnitTests/Find/Find_Selector_Conditions.cs
Closes #47 
Enums in arrays were being serialized by their name (`{"selector":{"species":{"$in":[Human,Droid]}}}`), which wasn't consistent with other places enums were serialized for queries (`{"selector":{"species":{"$in":[0,1]}}}`). This changes it to serialize as an int
=> $in queries with enums serialized as ints

.gitignore, CHANGELOG.md, LATEST_CHANGE.md, src/CouchDB.Driver/CouchClient.cs, src/CouchDB.Driver/CouchDatabase.cs, src/CouchDB.Driver/CouchQueryProvider.cs, src/CouchDB.Driver/QueryTranslator.cs, tests/CouchDB.Driver.E2ETests/Client_Tests.cs, tests/CouchDB.Driver.UnitTests/Client_Tests.cs
Escape special character in database names
=> Bug fix: Escape special character in database names.

src/CouchDB.Driver/CouchDatabase.cs
=> fix FindManyAsync crash on non-existing documents

src/CouchDB.Driver/Helpers/CouchContractResolver.cs, src/CouchDB.Driver/Views/CouchViewOptions.cs, src/CouchDB.Driver/Views/StableStyle.cs
Hey as I was using it across a project and running some tests I came across some errors when using the `CouchViewOptions`.
So I changed all values to have a `null`  default value and also be Ignored by the serializer.
This fixes a bad request error for including values as null that don't support it on the server like the following
- `group_level`
- `keys`
- `limit`
Changed `stable` to use a class like `update` since I discovered it says that it is a boolean but it needs to be in a string form.
I used a view and a client like Postman and C# to test again all values and these were the only problem.
I believe leaving all values null and as part not included until a user sets them explicitly is better since it only sends the settings the user chooses to, the DB uses its defaults and it might …
=> Fix CouchViewOptions

README.md
Because of https://github.com/matteobortolazzo/couchdb-net/issues/120#issuecomment-795878283 - the field is now `split_discriminator`.
`troups` is a misspelling of `troops`
`slit` => `split`
=> Update name of discriminator field to `split_discriminator` and other minor corrections

src/CouchDB.Driver/Query/Translators/MethodCallExpressionTranslator.cs, tests/CouchDB.Driver.UnitTests/Find/Find_Selector_Conditions.cs
Add support for regex multiline, via Any IsMatch.
It's very important to keep existing functionality as before, so this was covered by unit tests, for a single string, but also for a collection of strings.
=> Add support for regex multiline, via Any IsMatch

src/CouchDB.Driver/Converters/AttachmentsParsedConverter.cs, src/CouchDB.Driver/Types/CouchDocument.cs
Fixes #163 
CouchDB v3.2.1 (in my test scenario) refuses a document update when one or more  attachments were added because of incomplete attachment meta data created by the serializer. I solved this by adding a JSON converter which ignores new attachments in the PUT request.
=> Fixes Bad Request on Attachment Upload

src/CouchDB.Driver/Types/Sizes.cs
If you call `GetInfoAsync()` on a database that exceeds 2 GB you'll encounter the following issue:
```
Newtonsoft.Json.JsonReaderException: 'JSON integer 5111222718 is too large or small for an Int32. Path 'sizes.file', line 1, position 294.'
```
This PR simply switches the relevant fields from `int` to `long` which fixes the error.
=> Fixed 32-bit integer overflow in GetInfoAsync()

README.md, src/CouchDB.Driver/CouchDatabase.cs, src/CouchDB.Driver/DatabaseApiMethodOptions/AddOptions.cs, src/CouchDB.Driver/DatabaseApiMethodOptions/AddOrUpdateOptions.cs, src/CouchDB.Driver/DatabaseApiMethodOptions/FindOptions.cs, src/CouchDB.Driver/ICouchDatabase.cs, tests/CouchDB.Driver.E2ETests/README.txt, tests/CouchDB.Driver.UnitTests/Database_Tests.cs
Revisions are essential feature for MVCC in CouchDB. Passing a revision to PUT request makes you aware of the conflict (if happen) via response [409 Conflict](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10) from CouchDB HTTP API. That's why we need to support passing revisions to `AddOrUpdate` method.
To avoid breaking changes with my addition and while more request options might be introduced in future, I contributed to `DatabaseApiMethodOptions` namespace and:
- added `FindOptions` + `ICouchDatabase<TSource>.FindAsync` paired method
- added `AddOrUpdateOptions` + `ICouchDatabase<TSource>.AddOrUpdateAsync` paired method 
- added `AddOptions` + `ICouchDatabase<TSource>.AddAsync` paired method
I suppose in the future another contributors whould't extend method …
=> Support for revisions in Find, AddOrUpdate

src/CouchDB.Driver/ICouchClient.cs
`ICouchClient` is missing the definitions for replication methods, I've added them with API XML docs.
=> Added missing replication methods to client interface

src/CouchDB.Driver/CouchDatabase.cs, src/CouchDB.Driver/ICouchDatabase.cs, src/CouchDB.Driver/Types/CouchAttachment.cs, src/azure-pipelines.yaml
This fixes #194. When a user requests the full document and attachments to be included in the change feed response, the Base64 encoded data blob of the attachment is now returned so the document can be inserted unaltered into a different database.
I think the chosen approach both conserves backwards compatibility and makes the change feed behave as expected.
- Added XML documentation to `CouchAttachment` class
- Changed `int` to `long` to support attachments greater than the Int32 size limitation
- Added missing properties to `CouchAttachment` class:
- `EncodedLength `
- `Data` 
- Added HTTP header `Accept: application/json` where applicable
- Fixed a nullable warning
- Add tests
=> Implements fetching attachment data when requested in continuous change feed

CHANGELOG.md, LATEST_CHANGE.md, src/CouchDB.Driver/CouchDatabase.cs, src/azure-pipelines.yaml
Fixes https://github.com/matteobortolazzo/couchdb-net/issues/198
=> Changes GetChangesAsync to indefinitely auto-recover until cancellation is signalled
